/*

 BKGNORMALDATA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 36
   Tile set      : C:\Users\vinic\Documents\Programacao\GameBoy\gbdk\bkgnormal.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BkgNormalWidth 20
#define BkgNormalHeight 36
#define BkgNormalBank 0

extern unsigned char BkgNormal[];

/* End of BKGNORMALDATA.H */
